services:
  - type: web
    name: cohabitify
    env: node
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install --include=dev && npm run build && cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: "<your-mongodb-uri>"
      - key: JWT_SECRET
        value: "<your-jwt-secret>"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "<your-smtp-user>"
      - key: SMTP_PASS
        value: "<your-smtp-pass>"
      - key: ALLOWED_ORIGINS
        value: "https://cohabify-6efc.onrender.com"
